Bug: ColWidth_Converter wasn't imported
ColWidth_Converter was not added to __init__.py that leads to
error:

```
    converted = CONVERTER_TABLE[type(child)].convert(context, child)
KeyError: ColWidth_(Double)
```

The commit also fixes DoubleConverter which is never used so no one
see an error:

```
    for child_index, child in enumerate(target):
TypeError: 'float' object is not iterable
```